services:
  web:
    container_name: soen331-app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS
      - SOEN_341_PASSWORD
  redis:
    image: redis:latest